name: httpp
description: flutter lib for parallel http req
version: 0.0.7
homepage: https://mytiki.com
repository: https://github.com/tiki/httpp
issue_tracker: https://github.com/tiki/httpp/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.6
  http: ^0.13.4
  logging: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter